#!/bin/bash

source .venv/bin/activate
source .profile

airflow users create \
    --username admin \
    --role Admin \
    --password admin \
    \
    --email "" \
    --firstname "" \
    --lastname ""