[project]
name = "airflow-project"
version = "0.1.0"
description = "Configuration project for airflow"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow>=3.0.2",
    "apache-airflow-providers-fab>=2.2.0",
    "configparser>=7.2.0",
    "pandas>=2.3.0",
]
