#!/bin/bash

source .venv/bin/activate
source .profile

SESSION_NAME=$AIRFLOW_TMUX_SESSION_NAME

if tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
    echo "A tmux session with name $SESSION_NAME already exist. skipping session creation."
    
else
    echo "Creating tmux session '$SESSION_NAME'."

    tmux new-session -d -s airflow -n editor \; \
        send-keys 'airflow scheduler' C-m \; \
        new-window -n server \; \
        send-keys 'airflow dag-processor' C-m \; \
        new-window -n logs \; \
        send-keys 'airflow api-server' C-m
fi

echo "Airflow session on tmux at: $SESSION_NAME"
